name: Check and Build

on:
  workflow_call:

permissions:
  contents: read
  packages: read

env:
  JAVA_DISTRIBUTION: zulu
  JAVA_VERSION: "21"
  GPR_TOKEN: ${{ secrets.SCANNER_PACKAGES_TOKEN }}

jobs:
  lint:
    name: Spotless check
    runs-on: self-hosted-android
    steps:
      - &checkout
        name: Check out code
        uses: actions/checkout@v6

      - &setup-jdk
        name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - &prepare-gradle
        name: Prepare Gradle wrapper
        run: |
          tr -d '\r' < gradlew > gradlew.tmp && mv gradlew.tmp gradlew
          chmod +x ./gradlew

      - name: Spotless
        run: ./gradlew spotlessCheck

  test:
    needs: lint
    runs-on: self-hosted-android
    steps:
      - *checkout
      - *setup-jdk

      - &setup-android
        name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - *prepare-gradle

      - name: Test
        run: ./gradlew test

  build:
    needs: test
    runs-on: self-hosted-android
    steps:
      - *checkout
      - *setup-jdk
      - *setup-android
      - *prepare-gradle

      - name: Build with Gradle
        run: ./gradlew buildDevDebug
