name: Check and Build

on:
  workflow_call:

jobs:
  lint:
    name: Spotless check
    runs-on: self-hosted-android
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 17

      - name: Make Gradle executable
        run: |
          tr -d '\r' < gradlew > gradlew.tmp && mv gradlew.tmp gradlew
          chmod +x ./gradlew

      - name: Spotless
        run: ./gradlew spotlessCheck

  test:
    needs: lint
    if: ${{ needs.lint.result == 'success' }}
    runs-on: self-hosted-android
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Make Gradle executable
        run: |
          tr -d '\r' < gradlew > gradlew.tmp && mv gradlew.tmp gradlew
          chmod +x ./gradlew

      - name: Test
        run: ./gradlew test

  build:
    needs: test
    if: ${{ needs.test.result == 'success' }}
    runs-on: self-hosted-android
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Make Gradle executable
        run: |
          tr -d '\r' < gradlew > gradlew.tmp && mv gradlew.tmp gradlew
          chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew buildDevDebug

      - name: Generate directory tree
        run: |
          tree -d -I '.git|src|build|.gradle|gradle|build-logic' --noreport > tree.txt

      - name: Update README
        run: |
          awk '
            /<!-- TREE_START -->/ {
            print "<!-- TREE_START -->"
            print "```"
            system("cat tree.txt")
            print "```"
            print "<!-- TREE_END -->"
            skip=1
            next
          }
          /<!-- TREE_END -->/ {
            skip=0
            next
          }
          !skip { print }
          ' README.md > README.tmp && mv README.tmp README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md || true
          git commit -m "Update README.md with project structure" || echo "No changes to commit"
          git push