name: Update Project Structure

on:
  workflow_call:


jobs:
  chore:
    runs-on: self-hosted-android
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate directory tree
        run: |
          tree -d -I '.git|src|build|.gradle|gradle|build-logic' --noreport > tree.txt

      - name: Update README
        run: |
          awk '
            /<!-- TREE_START -->/ {
            print "<!-- TREE_START -->"
            print "```"
            system("cat tree.txt")
            print "```"
            print "<!-- TREE_END -->"
            skip=1
            next
          }
          /<!-- TREE_END -->/ {
            skip=0
            next
          }
          !skip { print }
          ' README.md > README.tmp && mv README.tmp README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md || true
          git commit -m "Update README.md with project structure" || echo "No changes to commit"
          git push